version: '3.8'  
services:  
  postgres:  
    image: postgres:13  
    environment:  
      POSTGRES_USER: prisma  
      POSTGRES_PASSWORD: prisma  
      POSTGRES_DB: prisma  
    ports:  
      - "5432:5432"  
    volumes:  
      - postgres-data:/var/lib/postgresql/data  

volumes:  
  postgres-data: 
